name: Nightly Build (macOS)

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    concurrency: nightly-macos-${{ github.workflow }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch tags
        run: git fetch --tags --force

      - name: Check changes since last nightly
        id: diff
        shell: bash
        run: |
          TAG=nightly-macos-latest
          if git rev-parse -q --verify "refs/tags/$TAG" >/dev/null; then
            if git diff --quiet "$TAG"...HEAD -- .; then
              echo "skip=true" >> "$GITHUB_OUTPUT"
            fi
          fi

      - name: No changes — skip build
        if: steps.diff.outputs.skip == 'true'
        run: echo "No changes since last nightly. Skipping."

      - name: Set up Common Lisp environment
        if: steps.diff.outputs.skip != 'true'
        run: |
          brew install sbcl
          curl -O https://beta.quicklisp.org/quicklisp.lisp
          sbcl --non-interactive --load quicklisp.lisp --eval "(quicklisp-quickstart:install)"
          curl -L https://qlot.tech/installer | sh
          echo "$HOME/.qlot/bin" >> $GITHUB_PATH

      - name: Build Lem executable
        if: steps.diff.outputs.skip != 'true'
        run: scripts/macos-deploy.bash

      - name: Get current date
        if: steps.diff.outputs.skip != 'true'
        id: date
        run: echo "date=$(date +'%Y%m%d-%H%M')" >> "$GITHUB_OUTPUT"

      - name: Move/update nightly tag to current commit
        if: steps.diff.outputs.skip != 'true'
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag -f nightly-macos-latest
          git push -f origin nightly-macos-latest

      - name: Create/Update nightly pre-release
        if: steps.diff.outputs.skip != 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nightly-macos-latest
          name: Nightly Build (macOS) - ${{ steps.date.outputs.date }}
          prerelease: true
          generate_release_notes: false
          files: |
            bin/lem.app
