name: Nightly Build (Linux)

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: nightly-${{ github.workflow }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch tags
        run: git fetch --tags --force

      - name: Check changes since last nightly
        if: github.event_name != 'workflow_dispatch'
        id: diff
        shell: bash
        run: |
          TAG=nightly-latest
          if git rev-parse -q --verify "refs/tags/$TAG" >/dev/null; then
            if git diff --quiet "$TAG"...HEAD -- .; then
              echo "skip=true" >> "$GITHUB_OUTPUT"
            fi
          fi

      - name: No changes — skip build
        if: steps.diff.outputs.skip == 'true'
        run: echo "No changes since last nightly. Skipping."

      - name: Set up Docker Buildx
        if: steps.diff.outputs.skip != 'true'
        uses: docker/setup-buildx-action@v3

      - name: Build AppImage
        if: steps.diff.outputs.skip != 'true'
        run: make AppImage

      - name: Get current date
        if: steps.diff.outputs.skip != 'true'
        id: date
        run: echo "date=$(date +'%Y%m%d-%H%M')" >> "$GITHUB_OUTPUT"

      - name: Move/update nightly tag to current commit
        if: steps.diff.outputs.skip != 'true'
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag -f nightly-latest
          git push -f origin nightly-latest

      - name: Create/Update nightly pre-release
        if: steps.diff.outputs.skip != 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nightly-latest
          name: Nightly Build (Linux) - ${{ steps.date.outputs.date }}
          prerelease: true
          generate_release_notes: false
          files: |
            artifacts/Lem-x86_64.AppImage
